### ISSUE TITLE
open func moveItem(at fromIndex: Int, inParent oldParent: Any?, to toIndex: Int, inParent newParent: Any?) in NSOutlineView

### ISSUE THREAD

**Issue by AKGupta31** [dzmitry-antonenka/SwiftListTreeDataSource#2]
How to move a particular item in following cases:
1. From one parent to another like NSOutlineView
2. From no parent to child some item at particular index
3. From child of some item to root item at particular index

Basically i want some method similar to 
open func moveItem(at fromIndex: Int, inParent oldParent: Any?, to toIndex: Int, inParent newParent: Any?)
in NSOutlineView

**Comment by dzmitry-antonenka** [comment]
Hello @AKGupta31 , please review #3 and feel free to test, propose or contribute what's missing. Thank you!

**Comment by dzmitry-antonenka** [comment]
@AKGupta31 , I also think [fold](https://github.com/dzmitry-antonenka/SwiftListTreeDataSource/pull/3/commits/506bf9035b6cb5ada4feb817398a62e75d2a795e) would be nice addition. E.g. user applied some changes with drag&drop and we'd like to store or send somewhere.

**Comment by AKGupta31** [comment]
Hi @dzmitry-antonenka ...can you explain fold little more?. Also #3 is working fine as per my testing

**Comment by dzmitry-antonenka** [comment]
Thanks @AKGupta31 , happy it's provides necessary functionality. 

Regarding fold, from [Wikipedia](https://en.wikipedia.org/wiki/Fold_(higher-order_function)), also great article by [objc.io](https://talk.objc.io/episodes/S01E150-the-origins-of-reduce) and example from there. It's like well-known `reduce`, but `leaf` (also called empty) called for very bottom element assembling result like it was `in-order` operation. 

Example:
```
indirect enum List<Element> {
    case empty
    case cons(Element, List)

    func fold<Result>(_ emptyCase: Result, _ consCase: (Element, Result) -> Result) -> Result {
        switch self {
        case .empty:
            return emptyCase
        case let .cons(x, xs):
            // non-tail recursive, I like to think of this like folding deck of cards, in-order
            return consCase(x, xs.fold(emptyCase, consCase))
        }
    }

    func reduce<Result>(_ emptyCase: Result, _ consCase: (Element, Result) -> Result) -> Result {
        switch self {
        case .empty:
            return emptyCase
        case let .cons(x, xs):
            // Reduces `x` with `emptyCase` right away with following tail-recursive call.
            return xs.reduce(consCase(x, emptyCase), consCase)
        }
    }
}

// Check-out dump output of `reduce`. Hint: reversed list because of tail-recursive calls (1 nested first, 2 wraps it, 3 wraps 2 and nested 1...)
dump(
[1,2,3,4].reduce(List.empty, { .cons($1, $0) })
)

// Check-out dump output of `fold`. Output: list identity
let list = List<Int>.cons(1, .cons(2, .cons(3, .cons(4, .empty))))
dump(
    list.fold(List<Int>.empty, { List<Int>.cons($0, $1) })
)
```

**Comment by dzmitry-antonenka** [comment]
@AKGupta31 the bottom line it to assemble final tree after all the changes. Signature quite generic since we don't know final result type consumer wants. Please see examples in [ListTreeDataSource+BasicTests.swift test_move_withOneElementToParent_shouldChildBecomeSecondRoot](https://github.com/dzmitry-antonenka/SwiftListTreeDataSource/pull/3/files#diff-a8816c53c54755c28b0ad7c035c72b0eb56d00083b567e80f5c530ca8e226220) 

Use case: user updated inventory by moving around items and removing something, we'd like final tree state so we can encode it and send back to server.

**Comment by dzmitry-antonenka** [comment]
Adressed in #3
